"""Forecast generation workflows for persisted N-BEATS models."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd

from energy_forecast.models import NBeatsModel
from energy_forecast.storage import build_forecast_artifact_paths, save_dataframe, save_json


@dataclass(frozen=True)
class ForecastRunResult:
    """Artifacts generated by one forecast run."""

    forecast: pd.DataFrame
    forecast_path: Path
    forecast_input_path: Path
    metadata_path: Path
    model_id: str
    run_id: str


def generate_nbeats_forecast(
    *,
    app_root: str | Path,
    model_path: str | Path,
    context: pd.DataFrame,
    dataset_name: str,
    run_id: str | None = None,
    overwrite: bool = False,
) -> ForecastRunResult:
    """Load a saved N-BEATS model, forecast from context, and persist artifacts."""
    model = NBeatsModel.load(model_path)
    prepared_context = NBeatsModel._prepare_series(context)
    if len(prepared_context) < model.input_size:
        raise ValueError(
            f"context must include at least input_size={model.input_size} rows"
        )

    forecast_input = prepared_context.tail(model.input_size).reset_index(drop=True)
    forecast = model.predict_from_context(forecast_input, model.horizon)

    root = Path(app_root)
    model_id = Path(model_path).name
    paths = build_forecast_artifact_paths(root, model_id=model_id, run_id=run_id)

    save_dataframe(forecast_input, paths.forecast_input_path, overwrite=overwrite)
    save_dataframe(forecast, paths.forecast_path, overwrite=overwrite)
    save_json(
        {
            "dataset": dataset_name,
            "model": "nbeats",
            "model_id": paths.model_id,
            "run_id": paths.run_id,
            "model_path": str(model_path),
            "model_relative_path": _relative_to_root(Path(model_path), root),
            "horizon": model.horizon,
            "input_size": model.input_size,
            "generated_at": datetime.now(UTC).isoformat(),
            "input_rows": len(forecast_input),
            "forecast_rows": len(forecast),
            "last_input_timestamp": forecast_input["timestamp"].iloc[-1].isoformat(),
            "first_forecast_timestamp": forecast["timestamp"].iloc[0].isoformat(),
            "forecast_input_path": str(paths.forecast_input_path),
            "forecast_input_relative_path": _relative_to_root(
                paths.forecast_input_path, root
            ),
            "forecast_path": str(paths.forecast_path),
            "forecast_relative_path": _relative_to_root(paths.forecast_path, root),
            "compute": model.compute,
        },
        paths.metadata_path,
        overwrite=overwrite,
    )

    return ForecastRunResult(
        forecast=forecast,
        forecast_path=paths.forecast_path,
        forecast_input_path=paths.forecast_input_path,
        metadata_path=paths.metadata_path,
        model_id=paths.model_id,
        run_id=paths.run_id,
    )


def _relative_to_root(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)
