"""Forecast generation workflows for persisted N-BEATS models."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd

from energy_forecast.models import NBeatsModel
from energy_forecast.storage import build_run_id, safe_artifact_name, save_dataframe, save_json


@dataclass(frozen=True)
class ForecastRunResult:
    """Artifacts generated by one forecast run."""

    forecast: pd.DataFrame
    forecast_path: Path
    forecast_input_path: Path
    metadata_path: Path
    run_id: str


def generate_nbeats_forecast(
    *,
    app_root: str | Path,
    model_path: str | Path,
    context: pd.DataFrame,
    dataset_name: str,
    run_id: str | None = None,
    overwrite: bool = False,
) -> ForecastRunResult:
    """Load a saved N-BEATS model, forecast from context, and persist artifacts."""
    model = NBeatsModel.load(model_path)
    prepared_context = NBeatsModel._prepare_series(context)
    if len(prepared_context) < model.input_size:
        raise ValueError(
            f"context must include at least input_size={model.input_size} rows"
        )

    forecast_input = prepared_context.tail(model.input_size).reset_index(drop=True)
    forecast = model.predict_from_context(forecast_input, model.horizon)

    resolved_run_id = safe_artifact_name(run_id or build_run_id())
    root = Path(app_root)
    basename = f"{safe_artifact_name(dataset_name)}_nbeats_h{model.horizon}_{resolved_run_id}"
    forecast_input_path = root / "data" / "forecast_inputs" / f"{basename}_input.csv"
    forecast_path = root / "data" / "forecasts" / f"{basename}.csv"
    metadata_path = root / "data" / "forecast_runs" / f"{basename}.json"

    save_dataframe(forecast_input, forecast_input_path, overwrite=overwrite)
    save_dataframe(forecast, forecast_path, overwrite=overwrite)
    save_json(
        {
            "dataset": dataset_name,
            "model": "nbeats",
            "model_path": str(model_path),
            "horizon": model.horizon,
            "input_size": model.input_size,
            "generated_at": datetime.now(UTC).isoformat(),
            "input_rows": len(forecast_input),
            "forecast_rows": len(forecast),
            "last_input_timestamp": forecast_input["timestamp"].iloc[-1].isoformat(),
            "first_forecast_timestamp": forecast["timestamp"].iloc[0].isoformat(),
            "forecast_input_path": str(forecast_input_path),
            "forecast_path": str(forecast_path),
        },
        metadata_path,
        overwrite=overwrite,
    )

    return ForecastRunResult(
        forecast=forecast,
        forecast_path=forecast_path,
        forecast_input_path=forecast_input_path,
        metadata_path=metadata_path,
        run_id=resolved_run_id,
    )
