"""Training workflows for model artifacts."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

import pandas as pd

from energy_forecast.models import NBeatsModel
from energy_forecast.models.compute import compute_metadata, compute_trainer_kwargs
from energy_forecast.storage import build_artifact_paths, save_json

SelectionMode = Literal["all", "first_n", "row_range", "date_range"]


@dataclass(frozen=True)
class TrainingResult:
    """Artifacts generated by one training run."""

    model_path: Path
    training_input_path: Path
    metadata_path: Path
    model_id: str
    model: NBeatsModel


def select_training_data(
    series: pd.DataFrame,
    *,
    mode: SelectionMode = "all",
    first_n: int | None = None,
    start_row: int | None = None,
    end_row: int | None = None,
    start_timestamp: str | pd.Timestamp | None = None,
    end_timestamp: str | pd.Timestamp | None = None,
) -> pd.DataFrame:
    """Select a chronological training slice from a timestamp/y dataframe."""
    prepared = NBeatsModel._prepare_series(series)

    if mode == "all":
        return prepared

    if mode == "first_n":
        if first_n is None or first_n <= 0:
            raise ValueError("first_n must be greater than zero")
        return prepared.iloc[:first_n].reset_index(drop=True)

    if mode == "row_range":
        if start_row is None or end_row is None:
            raise ValueError("start_row and end_row are required for row_range")
        if start_row < 0 or end_row <= start_row:
            raise ValueError("row_range must satisfy 0 <= start_row < end_row")
        return prepared.iloc[start_row:end_row].reset_index(drop=True)

    if mode == "date_range":
        if start_timestamp is None or end_timestamp is None:
            raise ValueError("start_timestamp and end_timestamp are required for date_range")
        start = pd.to_datetime(start_timestamp, utc=True)
        end = pd.to_datetime(end_timestamp, utc=True)
        if end < start:
            raise ValueError("end_timestamp must be greater than or equal to start_timestamp")
        selected = prepared.loc[
            (prepared["timestamp"] >= start) & (prepared["timestamp"] <= end)
        ]
        return selected.reset_index(drop=True)

    raise ValueError(f"unsupported selection mode: {mode}")


def train_nbeats_model(
    *,
    app_root: str | Path,
    title: str,
    dataset_name: str,
    source_file: str | Path | None,
    series: pd.DataFrame,
    horizon: int,
    input_size: int | None = None,
    max_steps: int = 100,
    freq: str = "H",
    model_kwargs: dict[str, Any] | None = None,
    selection_mode: SelectionMode = "all",
    selection_metadata: dict[str, Any] | None = None,
    description: str | None = None,
    model_id: str | None = None,
    overwrite_model: bool = False,
    compute_device: str | None = None,
) -> TrainingResult:
    """Train N-BEATS and persist the model plus exact training input."""
    model_kwargs = dict(model_kwargs or {})
    selection_metadata = dict(selection_metadata or {})
    clean_description = (description or "").strip()
    clean_title = title.strip()
    if not clean_title:
        raise ValueError("title is required")

    paths = build_artifact_paths(app_root, model_id=model_id)
    model_kwargs.setdefault("default_root_dir", str(paths.model_dir / "logs" / "training"))
    compute_kwargs = compute_trainer_kwargs(compute_device)
    for key, value in compute_kwargs.items():
        model_kwargs.setdefault(key, value)
    model = NBeatsModel(
        horizon=horizon,
        freq=freq,
        input_size=input_size,
        max_steps=max_steps,
        model_kwargs=model_kwargs,
    )
    train_df = select_training_data(
        series,
        mode=selection_mode,
        **_selection_kwargs(selection_mode, selection_metadata),
    )
    _validate_training_size(train_df, model.input_size, horizon)

    _validate_artifact_outputs(
        paths.model_dir,
        paths.metadata_path,
        overwrite=overwrite_model,
    )

    model.fit(train_df)
    model.save(paths.model_dir, overwrite=overwrite_model)

    metadata = {
        "id": paths.model_id,
        "title": clean_title,
        "dataset": dataset_name,
        "model": "nbeats",
        "model_id": paths.model_id,
        "trained_at": datetime.now(UTC).isoformat(),
        "source_file": str(source_file) if source_file is not None else None,
        "source_file_name": Path(source_file).name if source_file is not None else None,
        "selection_mode": selection_mode,
        "selection_metadata": selection_metadata,
        "description": clean_description,
        "training_slice": _training_slice_metadata(series, train_df),
        "train_rows": len(train_df),
        "start_timestamp": train_df["timestamp"].iloc[0].isoformat(),
        "end_timestamp": train_df["timestamp"].iloc[-1].isoformat(),
        "logs_path": str(paths.model_dir / "logs" / "training"),
        "compute": compute_metadata(compute_device),
    }
    save_json(metadata, paths.metadata_path, overwrite=overwrite_model)

    return TrainingResult(
        model_path=paths.model_dir,
        training_input_path=paths.training_input_path,
        metadata_path=paths.metadata_path,
        model_id=paths.model_id,
        model=model,
    )


def _selection_kwargs(
    selection_mode: SelectionMode,
    selection_metadata: dict[str, Any],
) -> dict[str, Any]:
    allowed_keys_by_mode = {
        "all": set(),
        "first_n": {"first_n"},
        "row_range": {"start_row", "end_row"},
        "date_range": {"start_timestamp", "end_timestamp"},
    }
    allowed_keys = allowed_keys_by_mode[selection_mode]
    unexpected_keys = set(selection_metadata).difference(allowed_keys)
    if unexpected_keys:
        unexpected = ", ".join(sorted(unexpected_keys))
        raise ValueError(
            f"unsupported selection metadata keys for {selection_mode}: {unexpected}"
        )
    return {key: value for key, value in selection_metadata.items() if value is not None}


def _validate_artifact_outputs(
    model_path: Path,
    metadata_path: Path,
    *,
    overwrite: bool,
) -> None:
    if overwrite:
        return

    existing_paths = [
        path
        for path in (model_path, metadata_path)
        if path.exists()
    ]
    if existing_paths:
        existing = ", ".join(str(path) for path in existing_paths)
        raise FileExistsError(f"artifact already exists: {existing}")


def _validate_training_size(series: pd.DataFrame, input_size: int, horizon: int) -> None:
    minimum_rows = input_size + horizon
    if len(series) < minimum_rows:
        raise ValueError(
            f"training data must include at least input_size + horizon rows ({minimum_rows})"
        )


def _training_slice_metadata(source: pd.DataFrame, selected: pd.DataFrame) -> dict[str, Any]:
    prepared = NBeatsModel._prepare_series(source)
    if selected.empty:
        return {
            "row_start": 0,
            "row_end": 0,
            "rows": 0,
            "start_timestamp": None,
            "end_timestamp": None,
        }

    start_timestamp = selected["timestamp"].iloc[0]
    end_timestamp = selected["timestamp"].iloc[-1]
    start_matches = prepared.index[prepared["timestamp"] == start_timestamp].tolist()
    end_matches = prepared.index[prepared["timestamp"] == end_timestamp].tolist()
    row_start = start_matches[0] if start_matches else 0
    row_end = (end_matches[-1] + 1) if end_matches else row_start + len(selected)
    return {
        "row_start": int(row_start),
        "row_end": int(row_end),
        "rows": int(len(selected)),
        "start_timestamp": start_timestamp.isoformat(),
        "end_timestamp": end_timestamp.isoformat(),
    }
