"""Training workflows for model artifacts."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

import pandas as pd

from energy_forecast.models import NBeatsModel
from energy_forecast.storage import build_artifact_paths, build_run_id, save_dataframe, save_json

SelectionMode = Literal["all", "first_n", "row_range", "date_range"]


@dataclass(frozen=True)
class TrainingResult:
    """Artifacts generated by one training run."""

    model_path: Path
    training_input_path: Path
    metadata_path: Path
    run_id: str
    model: NBeatsModel


def select_training_data(
    series: pd.DataFrame,
    *,
    mode: SelectionMode = "all",
    first_n: int | None = None,
    start_row: int | None = None,
    end_row: int | None = None,
    start_timestamp: str | pd.Timestamp | None = None,
    end_timestamp: str | pd.Timestamp | None = None,
) -> pd.DataFrame:
    """Select a chronological training slice from a timestamp/y dataframe."""
    prepared = NBeatsModel._prepare_series(series)

    if mode == "all":
        return prepared

    if mode == "first_n":
        if first_n is None or first_n <= 0:
            raise ValueError("first_n must be greater than zero")
        return prepared.iloc[:first_n].reset_index(drop=True)

    if mode == "row_range":
        if start_row is None or end_row is None:
            raise ValueError("start_row and end_row are required for row_range")
        if start_row < 0 or end_row <= start_row:
            raise ValueError("row_range must satisfy 0 <= start_row < end_row")
        return prepared.iloc[start_row:end_row].reset_index(drop=True)

    if mode == "date_range":
        if start_timestamp is None or end_timestamp is None:
            raise ValueError("start_timestamp and end_timestamp are required for date_range")
        start = pd.to_datetime(start_timestamp, utc=True)
        end = pd.to_datetime(end_timestamp, utc=True)
        if end < start:
            raise ValueError("end_timestamp must be greater than or equal to start_timestamp")
        selected = prepared.loc[
            (prepared["timestamp"] >= start) & (prepared["timestamp"] <= end)
        ]
        return selected.reset_index(drop=True)

    raise ValueError(f"unsupported selection mode: {mode}")


def train_nbeats_model(
    *,
    app_root: str | Path,
    dataset_name: str,
    source_file: str | Path | None,
    series: pd.DataFrame,
    horizon: int,
    input_size: int | None = None,
    max_steps: int = 100,
    freq: str = "H",
    model_kwargs: dict[str, Any] | None = None,
    selection_mode: SelectionMode = "all",
    selection_metadata: dict[str, Any] | None = None,
    run_id: str | None = None,
    overwrite_model: bool = False,
) -> TrainingResult:
    """Train N-BEATS and persist the model plus exact training input."""
    model_kwargs = dict(model_kwargs or {})
    model = NBeatsModel(
        horizon=horizon,
        freq=freq,
        input_size=input_size,
        max_steps=max_steps,
        model_kwargs=model_kwargs,
    )
    train_df = NBeatsModel._prepare_series(series)
    _validate_training_size(train_df, model.input_size, horizon)

    resolved_run_id = run_id or build_run_id()
    paths = build_artifact_paths(
        app_root,
        dataset_name=dataset_name,
        model_name="nbeats",
        horizon=horizon,
        run_id=resolved_run_id,
    )

    save_dataframe(train_df, paths.training_input_path)
    model.fit(train_df)
    model.save(paths.model_dir, overwrite=overwrite_model)

    metadata_path = paths.model_dir / "metadata.json"
    metadata = {
        "dataset": dataset_name,
        "model": "nbeats",
        "trained_at": datetime.now(UTC).isoformat(),
        "source_file": str(source_file) if source_file is not None else None,
        "selection_mode": selection_mode,
        "selection_metadata": dict(selection_metadata or {}),
        "train_rows": len(train_df),
        "start_timestamp": train_df["timestamp"].iloc[0].isoformat(),
        "end_timestamp": train_df["timestamp"].iloc[-1].isoformat(),
        "training_input_path": str(paths.training_input_path),
    }
    save_json(metadata, metadata_path)

    return TrainingResult(
        model_path=paths.model_dir,
        training_input_path=paths.training_input_path,
        metadata_path=metadata_path,
        run_id=resolved_run_id,
        model=model,
    )


def _validate_training_size(series: pd.DataFrame, input_size: int, horizon: int) -> None:
    minimum_rows = input_size + horizon
    if len(series) < minimum_rows:
        raise ValueError(
            f"training data must include at least input_size + horizon rows ({minimum_rows})"
        )
