[project]
name = "energy-forecast-desktop"
version = "0.1.0"
description = ""
authors = [
    {name = "andyalv",email = "andy.red02@gmail.com"},
    {name = "98beto", email = "esbjavo@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "pandas (>=2.2.0,<3.0.0)",
    "numpy (>=1.26.0,<2.0.0)",
    "flet (>=0.85.1,<0.86.0)",
    "neuralforecast (>=3.1.2,<4.0.0)",
    "torch (>=2.2.0,<3.0.0)",
    "flet-charts (>=0.85.1,<0.86.0)",
    "plotly (>=6.7.0,<7.0.0)",
]

[project.scripts]
app = "energy_forecast.desktop.app:run_app"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = true
packages = [
    { include = "energy_forecast", from = "src" }
]

[tool.flet.app]
path = "src"
